// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YourInterview.Services.Assessment.Infrastructure.Persistence;

#nullable disable

namespace YourInterview.Services.Assessment.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// 2026-09-15 第十七轮:手写迁移的配套 Designer。
    ///
    /// 手写原因:开发容器内无 dotnet SDK,无法执行 dotnet ef migrations add。
    /// BuildTargetModel 内容与当前 ModelSnapshot 一致 —— 本迁移就是最新一个,
    /// "迁移时的模型" 等于 "当前模型"。
    ///
    /// 验证(Forrest 的 Mac):
    ///   dotnet ef migrations list
    ///   dotnet ef migrations has-pending-model-changes   # 应无差异
    /// </summary>
    [DbContext(typeof(AssessmentDbContext))]
    [Migration("20260915220000_PracticeMaterialsAndRecordings")]
    partial class PracticeMaterialsAndRecordings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assessment")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YourInterview.Services.Assessment.Domain.PracticeMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsExpanded")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId", "ParentId", "SortOrder");

                    b.ToTable("practice_materials", "assessment");
                });

            modelBuilder.Entity("YourInterview.Services.Assessment.Domain.PracticeRecording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MaterialId", "CreatedAt");

                    b.ToTable("practice_recordings", "assessment");
                });

            modelBuilder.Entity("YourInterview.Services.Assessment.Domain.PracticeRecordingScore", b =>
                {
                    b.Property<Guid>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AccuracyScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("AssessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AzureRegion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("CompletenessScore")
                        .HasColumnType("double precision");

                    b.Property<double?>("FluencyScore")
                        .HasColumnType("double precision");

                    b.Property<double?>("PronScore")
                        .HasColumnType("double precision");

                    b.Property<double?>("ProsodyScore")
                        .HasColumnType("double precision");

                    b.Property<string>("RecognizedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WordsJson")
                        .HasColumnType("jsonb");

                    b.HasKey("RecordingId");

                    b.ToTable("practice_recording_scores", "assessment");
                });

            modelBuilder.Entity("YourInterview.Services.Assessment.Domain.SpeechSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("speech_settings", "assessment");
                });

            modelBuilder.Entity("YourInterview.Services.Assessment.Domain.DimensionIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Evidence")
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Suggestion")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Dimension");

                    b.HasIndex("QuestionId");

                    b.ToTable("dimension_issues", "assessment");
                });

            modelBuilder.Entity("YourInterview.Services.Assessment.Domain.MockQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerAudioPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double?>("AnswerDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<string>("AnswerTranscriptJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("AskedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BetterStructure")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("ExpectedPointsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("FillerWordsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendedAnswer")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ScoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence");

                    b.ToTable("mock_questions", "assessment");
                });

            modelBuilder.Entity("YourInterview.Services.Assessment.Domain.MockSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyStyle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("OverallSummary")
                        .HasColumnType("text");

                    b.Property<string>("PriorityAction")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TargetQuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Topic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("mock_sessions", "assessment");
                });

            modelBuilder.Entity("YourInterview.Services.Assessment.Domain.DimensionIssue", b =>
                {
                    b.HasOne("YourInterview.Services.Assessment.Domain.MockQuestion", null)
                        .WithMany("Issues")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourInterview.Services.Assessment.Domain.MockQuestion", b =>
                {
                    b.HasOne("YourInterview.Services.Assessment.Domain.MockSession", null)
                        .WithMany("Questions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("YourInterview.Services.Assessment.Domain.DimensionScores", "Scores", b1 =>
                        {
                            b1.Property<Guid>("MockQuestionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Fluency")
                                .HasColumnType("integer")
                                .HasColumnName("score_fluency");

                            b1.Property<int>("Pronunciation")
                                .HasColumnType("integer")
                                .HasColumnName("score_pronunciation");

                            b1.Property<int>("Relevance")
                                .HasColumnType("integer")
                                .HasColumnName("score_relevance");

                            b1.Property<int>("SentenceIntegrity")
                                .HasColumnType("integer")
                                .HasColumnName("score_sentence_integrity");

                            b1.Property<int>("Structure")
                                .HasColumnType("integer")
                                .HasColumnName("score_structure");

                            b1.Property<int>("TechnicalDepth")
                                .HasColumnType("integer")
                                .HasColumnName("score_technical_depth");

                            b1.HasKey("MockQuestionId");

                            b1.ToTable("mock_questions", "assessment");

                            b1.WithOwner()
                                .HasForeignKey("MockQuestionId");
                        });

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("YourInterview.Services.Assessment.Domain.MockQuestion", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("YourInterview.Services.Assessment.Domain.MockSession", b =>
                {
                    b.Navigation("Questions");
                });

            // 自引用:删父素材级联删子树
            modelBuilder.Entity("YourInterview.Services.Assessment.Domain.PracticeMaterial", b =>
                {
                    b.HasOne("YourInterview.Services.Assessment.Domain.PracticeMaterial", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            // 1:1:录音 → 评分(评分随录音删除)
            modelBuilder.Entity("YourInterview.Services.Assessment.Domain.PracticeRecording", b =>
                {
                    b.HasOne("YourInterview.Services.Assessment.Domain.PracticeRecordingScore", "Score")
                        .WithOne()
                        .HasForeignKey("YourInterview.Services.Assessment.Domain.PracticeRecordingScore", "RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Score");
                });
#pragma warning restore 612, 618
        }
    }
}
