// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YourInterview.Services.Interviews.Infrastructure.Persistence;

#nullable disable

namespace YourInterview.Services.Interviews.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InterviewsDbContext))]
    [Migration("20260914002703_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("interviews")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YourInterview.Services.Interviews.Domain.InterviewAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("InterviewEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("TranscriptSegmentsJson")
                        .HasColumnType("text");

                    b.Property<string>("TranscriptText")
                        .HasMaxLength(500000)
                        .HasColumnType("character varying(500000)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InterviewEntryId");

                    b.ToTable("assets", "interviews");
                });

            modelBuilder.Entity("YourInterview.Services.Interviews.Domain.InterviewEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisSummary")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<DateTimeOffset?>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CompanyProfile")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("FluencyScore")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("InterviewDate")
                        .HasColumnType("date");

                    b.Property<string>("InterviewFormat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Interviewers")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JdSummary")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("JdText")
                        .HasMaxLength(60000)
                        .HasColumnType("character varying(60000)");

                    b.Property<Guid?>("JobApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Notes")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<int?>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<int?>("PronunciationScore")
                        .HasColumnType("integer");

                    b.Property<int?>("RelevanceScore")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("RoundNo")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("StructureScore")
                        .HasColumnType("integer");

                    b.Property<int?>("TechnicalDepthScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TranscribedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyName");

                    b.HasIndex("InterviewDate");

                    b.HasIndex("Status");

                    b.ToTable("entries", "interviews");
                });

            modelBuilder.Entity("YourInterview.Services.Interviews.Domain.InterviewQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AskedAtSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Assessment")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("FollowUpQuestionsJson")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<bool>("GotStuck")
                        .HasColumnType("boolean");

                    b.Property<Guid>("InterviewEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("MissedPointsJson")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("MyAnswerText")
                        .HasMaxLength(60000)
                        .HasColumnType("character varying(60000)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("RecommendedAnswer")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("StuckReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("WeaknessTagsJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewEntryId");

                    b.HasIndex("InterviewEntryId", "Sequence");

                    b.ToTable("questions", "interviews");
                });

            modelBuilder.Entity("YourInterview.Services.Interviews.Domain.InterviewWeakness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Evidence")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid>("InterviewEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Suggestion")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("InterviewEntryId");

                    b.ToTable("weaknesses", "interviews");
                });

            modelBuilder.Entity("YourInterview.Services.Interviews.Domain.InterviewAsset", b =>
                {
                    b.HasOne("YourInterview.Services.Interviews.Domain.InterviewEntry", null)
                        .WithMany("Assets")
                        .HasForeignKey("InterviewEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourInterview.Services.Interviews.Domain.InterviewQuestion", b =>
                {
                    b.HasOne("YourInterview.Services.Interviews.Domain.InterviewEntry", null)
                        .WithMany("Questions")
                        .HasForeignKey("InterviewEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourInterview.Services.Interviews.Domain.InterviewWeakness", b =>
                {
                    b.HasOne("YourInterview.Services.Interviews.Domain.InterviewEntry", null)
                        .WithMany("Weaknesses")
                        .HasForeignKey("InterviewEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourInterview.Services.Interviews.Domain.InterviewEntry", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Questions");

                    b.Navigation("Weaknesses");
                });
#pragma warning restore 612, 618
        }
    }
}
