// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YourInterview.Services.Knowledge.Infrastructure.Persistence;

#nullable disable

namespace YourInterview.Services.Knowledge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KnowledgeDbContext))]
    partial class KnowledgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("knowledge")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YourInterview.Services.Knowledge.Domain.KnowledgeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BetterAnswer")
                        .HasColumnType("text");

                    b.Property<string>("CommonMistakesJson")
                        .HasColumnType("text");

                    b.Property<string>("ConceptExplanation")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<double>("EasinessFactor")
                        .HasColumnType("double precision");

                    b.Property<string>("FollowUpsJson")
                        .HasColumnType("text");

                    b.Property<int>("Importance")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyPointsJson")
                        .HasColumnType("text");

                    b.Property<int?>("LastIntervalDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mastery")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MyAnswer")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("ReferencesJson")
                        .HasColumnType("text");

                    b.Property<int>("RepetitionStreak")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SourceCompanyName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly?>("SourceDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("SourceInterviewEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubTopic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TagsJson")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Mastery");

                    b.HasIndex("NextReviewAt");

                    b.HasIndex("Source");

                    b.HasIndex("SourceInterviewEntryId");

                    b.HasIndex("Topic");

                    b.HasIndex("Mastery", "NextReviewAt");

                    b.ToTable("knowledge_items", "knowledge");
                });

            modelBuilder.Entity("YourInterview.Services.Knowledge.Domain.KnowledgeRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RelatedItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RelatedItemId");

                    b.HasIndex("ItemId", "RelatedItemId", "RelationType")
                        .IsUnique();

                    b.ToTable("knowledge_relations", "knowledge");
                });

            modelBuilder.Entity("YourInterview.Services.Knowledge.Domain.KnowledgeReviewLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ConfidenceAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("ConfidenceBefore")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ReviewedAt");

                    b.HasIndex("ItemId", "ReviewedAt");

                    b.ToTable("knowledge_review_logs", "knowledge");
                });

            modelBuilder.Entity("YourInterview.Services.Knowledge.Domain.KnowledgeRelation", b =>
                {
                    b.HasOne("YourInterview.Services.Knowledge.Domain.KnowledgeItem", null)
                        .WithMany("Relations")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourInterview.Services.Knowledge.Domain.KnowledgeReviewLog", b =>
                {
                    b.HasOne("YourInterview.Services.Knowledge.Domain.KnowledgeItem", null)
                        .WithMany("ReviewLogs")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourInterview.Services.Knowledge.Domain.KnowledgeItem", b =>
                {
                    b.Navigation("Relations");

                    b.Navigation("ReviewLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
